import img1 from "./Assets/img1.jpeg";
import img2 from "./Assets/img2.jpeg";
import img3 from "./Assets/img3.jpeg";
import img4 from "./Assets/img4.jpeg";
import img5 from "./Assets/img5.jpeg";
import img6 from "./Assets/img6.jpeg";

export const ShopData = [
  {
    img: img1,
    category: "Sustainable Materials",
    // name: "Nike Sportwear Essential",
    name: "Sportwear essential",
    description: "Women's High-Rise Woven Cargo Pants",
    nColor: "1 Color",
    Price: "$40",
  },
  {
    img: img2,
    category: "Sustainable Materials",
    name: "Nike Sportwear Essential",
    description: "Women's High-Rise Woven Cargo Pants",
    nColor: "1 Color",
    Price: "$40",
  },
  // {
  //   img: img3,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img4,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img5,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img6,
  //   category: "Best Seller",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img2,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img3,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img4,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img5,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img6,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img3,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img2,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img6,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img5,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img4,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img2,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img3,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img3,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img4,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img5,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img6,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img2,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img3,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40",
  // },
  // {
  //   img: img5,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img4,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img6,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$40"
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   Price: "$99.90"
  // },
  // {
  //   img: img1,
  //   category: "Sustainable Materials",
  //   name: "Nike Sportwear Essential",
  //   description: "Women's High-Rise Woven Cargo Pants",
  //   nColor: "1 Color",
  //   ifNoPrice: "Add to Bag for Price",
  // },
  {
    img: img1,
    category: "Sustainable Materials",
    name: "Nike Sportwear Essential",
    description: "Women's High-Rise Woven Cargo Pants",
    nColor: "1 Color",
    Price: "$70"
  },
];


